# Generated by Django 3.1.7 on 2021-03-28 00:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('num_players', models.IntegerField(default=1)),
                ('send_notifications', models.BooleanField(default=True)),
                ('days_of_week', models.CharField(max_length=30, validators=[django.core.validators.int_list_validator])),
                ('earliest_time', models.PositiveSmallIntegerField(default=6)),
                ('latest_time', models.PositiveSmallIntegerField(default=15)),
                ('torrey_north', models.BooleanField(default=True)),
                ('torrey_south', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
